---
- name: Install epel-release
  package:
    name: epel-release
    state: latest

- name: Install nginx
  package:
    name: nginx
    state: latest
    
- name: Create /etc/nginx/default.d/kickstart.conf
  template:
    src: kickstart.conf
    dest: /etc/nginx/default.d/kickstart.conf
    mode: 0600
    
- name: Creates /kickstart directory
  file: 
    path: "/kickstart"
    state: directory
    
- name: Creates /kickstart/stage directory
  file: 
    path: "/kickstart/stage"
    state: directory

- name: Create /kickstart/stage/resolv.conf
  template:
    src: resolv.conf
    dest: /kickstart/stage/resolv.conf
    owner: root
    group: root
    mode: 0644   

- name: Create /kickstart/stage/exports
  template:
    src: exports
    dest: /kickstart/stage/exports
    owner: root
    group: root
    mode: 0644   

- name: Create /kickstart/stage/ntp.conf
  template:
    src: ntp.conf
    dest: /kickstart/stage/ntp.conf
    owner: root
    group: root
    mode: 0644 
    
- name: Create /kickstart/stage/authorized_keys
  template:
    src: authorized_keys
    dest: /kickstart/stage/authorized_keys
    owner: root
    group: root
    mode: 0644     

- name: Create /kickstart/stage/overlay.conf
  copy:
    src: overlay.conf
    dest: /kickstart/stage/overlay.conf
    owner: root
    group: root
    mode: 0644 

- name: Create /kickstart/stage/ip_vs.conf
  copy:
    src: ip_vs.conf
    dest: /kickstart/stage/ip_vs.conf
    owner: root
    group: root
    mode: 0644 
    
- name: Create /kickstart/stage/docker.repo
  copy:
    src: docker.repo
    dest: /kickstart/stage/docker.repo
    owner: root
    group: root
    mode: 0644 
        
- name: Create /kickstart/stage/docker-override.conf
  copy:
    src: docker-override.conf
    dest: /kickstart/stage/docker-override.conf
    owner: root
    group: root
    mode: 0644
    
- name: Creates /kickstart/config directory
  file: 
    path: "/kickstart/config"
    state: directory
    
- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Enable nginx
  service:
    name: nginx
    enabled: yes    
