---
- name: "Install PXE server"
  hosts: pxeservers
  remote_user: root
  roles:
     - common
     - ntp
     - bind
#     - dns-client
     - dhcp    
     - tftp
     - tftp-centos7 
     - tftp-coreos
     - kickstart
     - ignition
     - hosts-config
