all:
  children:
    pxeservers:
      hosts: 192.168.40.10
  vars: 
    hosts_role_types: ["dcos-boot","dcos-master","dcos-slave","dcos-slave_public","nfs","k8s","glusterserver","generic"]
    hosts_time_zone: "Europe/Lisbon"
    hosts_root_pw: "Welcome1"
    hosts_keyboard: "pt-latin1"
    hosts_lang: "en_US.UTF-8"
    hosts_names: ["demobox","k8s-master1","k8s-node1","k8s-node2","k8s-node3"]
    hosts_distribution: ["centos7","centos7","centos7","centos7","centos7"]        
    hosts_ips: ["192.168.40.100","192.168.40.40","192.168.40.41","192.168.40.42","192.168.40.43"]
    #identificar qual é o MAC ADDR do PC de demonstração e substituir "00:00:00:00:00:00"
    hosts_mac_addrs: ["00:00:00:00:00:00","52:54:00:e2:87:5b","52:54:00:e2:87:5c","52:54:00:e2:87:5d","52:54:00:e2:87:5e"]
    hosts_roles: ["generic","k8s","k8s","k8s","k8s"]
    hosts_cluster_if: ["eth0","eth0","eth0","eth0","eth0"]
    hosts_use_pxe_dns: true
    hosts_network_mask: "255.255.255.0"
    bind_local_ip: "{{pxe_server_ip}}"
    bind_local_forwarder: "192.168.1.254"
    bind_local_network: "192.168.40.0/23"
    bind_local_zone_name: "demobox.local"
    bind_local_hostname: "pxe"
    dhcp_internal_router_ip: "192.168.40.1"
    dhcp_internal_broadcast: "192.168.40.255"
    dhcp_external_router_ip: "192.168.41.1"
    dhcp_external_broadcast: "192.168.41.255"
    dhcp_external_subnet: "192.168.41.0"
    dhcp_external_mask: "255.255.255.0"
    dhcp_external_range_start: "192.168.41.10"
    dhcp_external_range_end: "192.168.41.100"
    kickstart_ntp_server_name: "pool.ntp.org"
    kickstart_server_ip: "{{pxe_server_ip}}"
    kickstart_server_port: "80"
    kickstart_ssh_authorized_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC99wsmeQvMrH9mj16cZ9IlhS+AX45ZKEBZ/sNijatEmYTE3GnUs9l44l0xA1IgHbwpVBl71HvP/Wsy0F0TpsQNwfafCxlSXpmwFMTuULHSTRxMxPpitZDE60YFuPcEs/wnHWe+RMfAyo6u/q85blo1MEEbReeG6doELMHlovU0l5Tpe7Oj3uVZiFvRTlyoQqOrruXfxuoX6OcqMFgIxGbv8yVaMpdfaZc2+8B4DJ1HekYZiGpNvCYkm7TVWahk4saBSZ1GLLmiDeR3GLFMQQS0NHBLasQsXkfaVpAEN/xVFhtJLLiD/Woq6ytUlU1HcDbbUWEhzRl+Xv6PoT/zFdR5"
    tftp_server_ip: "{{pxe_server_ip}}"
    pxe_server_ip: "192.168.40.10"
    pxe_cluster_if: "eth0"

