---
- name: Add Docker repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/tmp"
  environment:
    http_proxy: "{{k8s_http_proxy_server}}"
    https_proxy: "{{k8s_http_proxy_server}}"      
    
- name: Install docker
  package:
    name: "{{k8s_docker_pkg}}"

- name: Start docker
  service:
    name: docker
    enabled: yes  
    state: started
    
- name: Install kubectl
  package:
    name: kubectl 
    state: latest
    disable_gpg_check: yes

- name: Install Ansible
  package:
    name: ansible
    state: latest
    disable_gpg_check: yes

# helm
